imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    file_directory: '%kernel.root_dir%/../web/uploads'

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
            - "bootstrap_3_layout.html.twig"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name_dev%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  utf8mb4
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\User

assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~
    assets:
            bootstrap_js:
                inputs:
                    - "%kernel.root_dir%/../src/AppBundle/Resources/public/js/bootstrap.min.js"
                output: "js/bootstrap_js.js"
            bootstrap_css:
                inputs:
                    - "%kernel.root_dir%/../src/AppBundle/Resources/public/css/bootstrap.min.css"
                    - "%kernel.root_dir%/../src/AppBundle/Resources/public/css/bootstrap-theme.min.css"
                output: "css/bootstrap_css.css"
                filters: [cssrewrite]
            bootstrap_glyphicons_ttf:
                inputs:
                    - "%kernel.root_dir%/../src/AppBundle/Resources/public/fonts/glyphicons-halflings-regular.ttf"
                output: "fonts/glyphicons-halflings-regular.ttf"
            bootstrap_glyphicons_eot:
                inputs:
                    - "%kernel.root_dir%/../src/AppBundle/Resources/public/fonts/glyphicons-halflings-regular.eot"
                output: "fonts/glyphicons-halflings-regular.eot"
            bootstrap_glyphicons_svg:
                inputs:
                    -  "%kernel.root_dir%/../src/AppBundle/Resources/public/fonts/glyphicons-halflings-regular.svg"
                output: "fonts/glyphicons-halflings-regular.svg"
            bootstrap_glyphicons_woff:
                inputs:
                    -  "%kernel.root_dir%/../src/AppBundle/Resources/public/fonts/glyphicons-halflings-regular.woff"
                output: "fonts/glyphicons-halflings-regular.woff"
            bootstrap_glyphicons_woff2:
                inputs:
                    -  "%kernel.root_dir%/../src/AppBundle/Resources/public/fonts/glyphicons-halflings-regular.woff2"
                output: "fonts/glyphicons-halflings-regular.woff2"

            jquery:
                inputs:
                    - "%kernel.root_dir%/../vendor/components/jquery/jquery.js"

            form_collection:
                inputs:
                  - "%kernel.root_dir%/../src/AppBundle/Resources/public/js/form_collection.js"
                output: "js/form_collection.js"
            exp_sub_type_selection_updater:
                inputs:
                  - "%kernel.root_dir%/../src/AppBundle/Resources/public/js/exp_sub_type_selection_updater.js"
                output: "js/exp_sub_type_selection_updater.js"
            set_nav_active_link:
                inputs:
                  - "%kernel.root_dir%/../src/AppBundle/Resources/public/js/set_nav_active_link.js"
                output: "js/set_nav_active_link.js"

            poem_css:
                inputs:
                   - "%kernel.root_dir%/../src/AppBundle/Resources/public/css/poem.css"
                output: "css/poem.css"
                filters: [cssrewrite]

            poem_logo:
                inputs:
                - "%kernel.root_dir%/../src/AppBundle/Resources/public/images/poem_logo.png"
                output: "poem_logo.png"

            summernote_css:
                inputs:
                  - "%kernel.root_dir%/../src/AppBundle/Resources/public/css/summernote.css"
                output: "css/summernote.css"
                filters: [cssrewrite]
            summernote_js:
                inputs:
                  - "%kernel.root_dir%/../src/AppBundle/Resources/public/js/summernote.min.js"
                output: "js/summernote.js"
            summernote_config_js:
                inputs:
                  - "%kernel.root_dir%/../src/AppBundle/Resources/public/js/summernote_config.js"
                output: "js/summernote_config.js"
            summernote_eot:
                inputs:
                  - "%kernel.root_dir%/../src/AppBundle/Resources/public/fonts/summernote.eot"
                output: "font/summernote.eot"
            summernote_ttf:
                inputs:
                  - "%kernel.root_dir%/../src/AppBundle/Resources/public/fonts/summernote.ttf"
                output: "font/summernote.ttf"
            summernote_woff:
                inputs:
                  - "%kernel.root_dir%/../src/AppBundle/Resources/public/fonts/summernote.woff"
                output: "font/summernote.woff"



