# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
  app.file_uploader:
          class: AppBundle\Uploader\FileUploader
          arguments: ['%file_directory%']

  app.version_manager:
          class: AppBundle\VersionManager\VersionManager
          arguments: ['@doctrine.orm.default_entity_manager', '@security.token_storage']

  app.doctrine_entity_listener:
          class: AppBundle\EventListener\EntityListener
          arguments: ['@app.file_uploader', '@logger']
          tags:
              - { name: doctrine.event_listener, event: prePersist }
              - { name: doctrine.event_listener, event: preUpdate }
              - { name: doctrine.event_listener, event: preRemove }

  app.user_manager:
            class: AppBundle\UserManager\UserManager
            arguments: ['@doctrine.orm.default_entity_manager', '%ldap_host%', '%ldap_port', '%ldap_username%', '%ldap_password%', '%ldap_baseDn_users%', '%ldap_domain_long%']

  app.biocontrol_manager:
          class: AppBundle\BioControl\BioControlManager
          arguments: ['@doctrine.dbal.bio_control_connection', '@doctrine.orm.default_entity_manager', '%ldap_domain_long%', '@app.user_manager']
